### PR TITLE
2 small fixes, ensuring all BSS VMAs are found and prevent data race

### PR DESCRIPTION
**Pull request by bpowers**
Hi @tongping!  I came across two small issues (I think) when reviewing
some of how DoubleTake works.  more info is in the commit messages
below.  Let me know if you see any problems, or if I've misunderstood
things!

### CODE REVIEW

**Comment by tongping** [comment]
Don't do that:-) I haven't  verified it.

-- 
Tongping Liu
Assistant Professor
CS, University of Texas at San Antonio
http://www.cs.utsa.edu/~tongpingliu/

**Comment by emeryberger** [comment]
I looked over the patches and they look solid (and are important fixes).


--
Professor Emery Berger
College of Information and Computer Sciences
University of Massachusetts Amherst
www.emeryberger.org, @emeryberger

**Comment by tongping** [comment]
I have confirmed these two changes. Changes on selfmap.h has to be fixed a
little bit.

The race won't happen in the second case. But the changes do make the code
more cleaner.

Done.

-- 
Tongping Liu
Assistant Professor
CS, University of Texas at San Antonio
http://www.cs.utsa.edu/~tongpingliu/

**Comment by bpowers** [comment]
Thanks for taking a look and confirming!

**Comment by bpowers** [comment]
just so I can do better in the future @tongping - what was the problem with the `isGlobals` test?

**Pull request merged**
